version: '3.8'
services:
  frontend:
    image: opavlov/frontend:0.2
    ports:
      - ${FRONT_PORT}:80
    env_file:
      - .env
    depends_on:
      - database
      - backend
    networks:
      - front-network
      - back-network
    restart: unless-stopped
  database:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${HOME}/docker-task/postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - back-network
    restart: unless-stopped
  backend:
    image: opavlov/backend:0.3
    ports:
      - ${BACK_PORT}:8000
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - back-network
    restart: unless-stopped
volumes:
  postgres_data:
networks:
  front-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.1.0/24
        gateway: 172.21.1.1
  back-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.2.0/24
        gateway: 172.21.2.1
